# Generated by Django 2.2.10 on 2021-05-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_historicalkyc_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkyc_info',
            name='blue_flag_temp',
        ),
    ]
