# Generated by Django 3.1.7 on 2021-04-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20210412_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='full_name_temp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='name_init_temp',
            field=models.CharField(max_length=100),
        ),
    ]
