# Generated by Django 3.2 on 2021-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20210421_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_info',
            name='profile_vid',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic/'),
        ),
    ]
