# Generated by Django 3.1.7 on 2021-04-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20210412_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='city_temp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='date_of_birth_temp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='house_no_temp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='id_type_temp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='mob_no_temp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='nationality_temp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='nics_no_temp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='occu_state_temp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='street_temp',
            field=models.CharField(max_length=20),
        ),
    ]
