# Generated by Django 3.2 on 2021-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_kyc_info_profile_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc_info',
            name='profile_vid',
        ),
        migrations.AddField(
            model_name='kyc_info',
            name='email_add_verification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
