# Generated by Django 3.2 on 2021-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_auto_20210429_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc_info',
            old_name='email_add_verification',
            new_name='email_add_temp',
        ),
        migrations.AddField(
            model_name='kyc_infotemp',
            name='email_add_verification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
