# Generated by Django 3.1.7 on 2021-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KycInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_init', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=50)),
                ('address_full', models.CharField(max_length=250)),
                ('email_add', models.CharField(max_length=250)),
                ('phone_num', models.CharField(max_length=12)),
                ('long_text', models.TextField(max_length=255)),
            ],
        ),
    ]
